sudo: false
cache:
  directories:
    - vendor/bundle
    - test/3.2/vendor/bundle
    - test/4.1/vendor/bundle
    - test/4.2/vendor/bundle
    - test/5.0/vendor/bundle
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
bundler_args: --without doc debug --path=vendor/bundle
env:
  matrix:
    - RAILS_VERSION=3.2
    - RAILS_VERSION=4.1
    - RAILS_VERSION=4.2
    - RAILS_VERSION=5.0
